spring.application.name=Wallets
# PostgreSQL

# =========================
# PostgreSQL JDBC (JPA)
# =========================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:wallet_db}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App
server.port=8081
