apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/wallet_db
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: admin
  SPRING_JPA_HIBERNATE_DDL_AUTO: update

  JWT_SECRET: your-super-secret-key-must-be-at-least-32-characters-long
  JWT_EXPIRATION: "86400000"